[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "3EZdSHXKEFFu91o6i4d7ERsVuK2aRWEZDzWfSPHP414a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/neonchick/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
